// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihcQ1IWU4AZmoOX-p5XcUJcMqQ9H3YYk',
    appId: '1:426149351816:web:b0898bc963071b74edea3d',
    messagingSenderId: '426149351816',
    projectId: 'blood-bank-c131f',
    authDomain: 'blood-bank-c131f.firebaseapp.com',
    storageBucket: 'blood-bank-c131f.firebasestorage.app',
    measurementId: 'G-F2MZVJE7G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjesF9aVPfGGKgTKCL4TpRiiVY7fKIb5Q',
    appId: '1:426149351816:android:195d8620427e3d9eedea3d',
    messagingSenderId: '426149351816',
    projectId: 'blood-bank-c131f',
    storageBucket: 'blood-bank-c131f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yBoCtKWevx1mmcqtfFxULLMrZl3wvo4',
    appId: '1:426149351816:ios:c235c21c2b76bebeedea3d',
    messagingSenderId: '426149351816',
    projectId: 'blood-bank-c131f',
    storageBucket: 'blood-bank-c131f.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8yBoCtKWevx1mmcqtfFxULLMrZl3wvo4',
    appId: '1:426149351816:ios:c235c21c2b76bebeedea3d',
    messagingSenderId: '426149351816',
    projectId: 'blood-bank-c131f',
    storageBucket: 'blood-bank-c131f.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBihcQ1IWU4AZmoOX-p5XcUJcMqQ9H3YYk',
    appId: '1:426149351816:web:3dce0561b98b688dedea3d',
    messagingSenderId: '426149351816',
    projectId: 'blood-bank-c131f',
    authDomain: 'blood-bank-c131f.firebaseapp.com',
    storageBucket: 'blood-bank-c131f.firebasestorage.app',
    measurementId: 'G-F0DSS5CJRT',
  );

}